### ISSUE TITLE
Make it possible for type functions to modify other type functions

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-type#27]
We should make it possible for something like this to work:

```js
import { type } from "can";

const MaybeConvertString = type.maybe( type.convert(String) );
```

This is needed for https://github.com/canjs/can-observable-bindings/issues/10 to be possible.

This would probably mean that the `[can.new]` that is generated by these functions should always be able to convert to the type instead of throwing if the type is supposed to be strict.

There would also need to be some way to specify that a type is strict, can be `null`, can be `undefined`, etc.

This would also mean that `canReflect.convert` would have to handle throwing if a strict type is set to an incorrect value.

Doing all of that would allow each function to handle only the things it needs to:

`can.canBeNull`, `can.isStrict`, and `can.canBeUndefined` are hypothetical Symbol names.

`type.maybe`
- set `can.isMember` and `can.new` Symbols only if they don't exist
- set `can.isStrict` to true only if it doesn't exist
- set `can.canBeNull` and `can.canBeUndefined` to true

`type.convert`
- set `can.isMember` and `can.new` Symbols only if they don't exist
- set `can.isStrict` to false
- set `can.canBeNull` and `can.canBeUndefined` to false only if they don't exist

`type.maybeConvert`
- set `can.isMember` and `can.new` Symbols only if they don't exist
- set `can.isStrict` to false
- set `can.canBeNull` and `can.canBeUndefined` to true

`type.check`
- set `can.isMember` and `can.new` Symbols only if they don't exist
- set `can.isStrict` to true
- set `can.canBeNull` and `can.canBeUndefined` to false only if they don't exist

**Comment by phillipskevin** [comment]
Here is a spreadsheet I put together that details how these different functions would modify the type metadata (`isStrict`, `canBeNull`, `canBeUndefined`): https://docs.google.com/spreadsheets/d/1IK6zF4UHLtiFBtjAU1dVOA7SBsotSEVvrtTw2_BZn_8/

**Comment by phillipskevin** [comment]
So I think the way this should work is we should add one new Symbol to the output of all of the `type` functions. 

So, for example, `type.maybe( String )` will return an object that looks like this:

```js
{
  ["can.new"]: function() {},
  ["can.isMember"]: function() {},
  ["can.typeInfo"]: {
    isStrict: true,
    canBeNull: true,
    canBeUndefined: true,
    OriginalType: String,
    transforms: [ "maybe" ]
  }
}
```

...`type.convert( type.maybe( String ) )` will return:

```js
{
  ["can.new"]: function() {},
  ["can.isMember"]: function() {},
  ["can.typeInfo"]: {
    isStrict: false,
    canBeNull: true,
    canBeUndefined: true,
    OriginalType: String,
    transforms: [ "maybe", "convert" ]
  }
}
```

The `isStrict`, `canBeNull`, and `canBeUndefined` properties would follow the logic explained above (and in the spreadsheet). `OriginalType` and the `transforms` array are so that we can show useful info in debug logs.

This would also allow us to add this functionality to `canReflect.convert` without a breaking change. If the type passed to `canReflect.convert` has this `typeInfo` Symbol then we can perform the new logic and `throw` errors if necessary. If the `typeInfo` Symbol does not exist, `canReflect.convert` will continue to use the existing logic and now `throw`.

**Comment by matthewp** [comment]
This is in major now.
