### ISSUE TITLE
Introduce a type.all

### ISSUE THREAD

**Issue by matthewp** [canjs/can-type#31]
It would be nice to be able to convert a Type, and all of its properties, without creating a whole new type and changing all of its keys. For example say you had a type like:

```js
class Person extends ObservableObject {
  static props = {
    first: String,
    last: String,
    age: Number
  }
}
```

In an environment where you only have string values, you would want `age` to be converted. 

----

This proposal is for a `type.all` that creates a new TypeObject with its own `getSchema` symbol. This symbol will change all keys. It takes a type function as its first argument.

In the above example you would do:

```js
const ConvertingPerson = type.all(type.convert, Person);
```

This gives flexibility so that `type.all(type.check)` is also possible, if for some reason you needed that sort of behavior.

Since converting is the most common need we've seen I also propose a `type.convertAll(Type)` sugar function.

**Comment by justinbmeyer** [comment]
Instead of a TypeObject, I was thinking these could operate on schemas.  This way we could easily overwrite a single property:

```js
fixture.store([ ...], { 
  ... type.convertSchema( Reflect.getSchema(Todo) ), 
  dueDate: {
    "can.new": function(date) {
        if( date === "yesterday" ) {
            return new Date()- 1000*24
        }
    }
  }
})
```

This was from my [notes in slack](https://bitovi.slack.com/archives/CHQA6LUQY/p1567632368044500) taken during the initial discussion of this problem.

This would require making `fixture.store()` able to take a schema.

**Comment by matthewp** [comment]
Your above suggestion is not a valid schema, I don't believe. You need a `keys` property, so an Object.assign({}) type of thing wouldn't be sufficient.

I suppose it could work like this:

```js
let schema = {
  ... type.convertSchema( Reflect.getSchema(Todo) ), 
};

schema.keys = { ...schema.keys, {
  dueDate: {
    "can.new": function(date) {
        if( date === "yesterday" ) {
            return new Date()- 1000*24
        }
    }
  }
});

fixture.store([ ...], schema);
```

You'd probably want some sort of `mergeSchemas` to make this nicer.  But this example begs the question of why you want this special type as part of the fixture schema but not part of the Type's property itself?

----

Regardless of a change in can-fixture to take a schema, the API proposed here would work equally well here:

```js
fixture.store([ ... ], { 
  ... Reflect.getSchema(type.convertAll(Todo)),
  dueDate: {
    "can.new": function(date) {
        if( date === "yesterday" ) {
            return new Date()- 1000*24
        }
    }
  }
});
```

**Comment by justinbmeyer** [comment]
> But this example begs the question of why you want this special type as part of the fixture schema but not part of the Type's property itself?

We are already creating special converting types for the fixtures. Services might want to do converting on params that a property should not support. As the example indicated, a server might want to support searching for dueDate=yesterday, but not support yesterday as a property value.

**Comment by justinbmeyer** [comment]
Basically sets (queries) are different from the items (records/fields) they test membership of.

**Comment by matthewp** [comment]
This is implemented in this branch: https://github.com/canjs/can-type/tree/type-all
