### ISSUE TITLE
Converting from an observation

### ISSUE THREAD

**Issue by matthewp** [canjs/can-type#4]
I'm not sure what should be happening here:

```js
canReflect.convert(observation, type.check(String))
```

Should it be left as an observation? Should it be unwrapped and checked?

**Comment by justinbmeyer** [comment]
Shouldn’t this throw an error?

**Comment by matthewp** [comment]
It currently does.

**Comment by matthewp** [comment]
What should be converting observations to values then?

**Comment by justinbmeyer** [comment]
> What should be converting observations to values then?

What do you mean?  

I think the following _should_ throw an error:

```
canReflect.convert(observation, type.check(String))
```

Can you provide example code for what you mean?

**Comment by matthewp** [comment]
Im looking to use can-bind with StacheDefineElement like you can with can-component. I guess can-component converts the observations to values. We don't have something like that for StacheDefineElement yet.

**Comment by matthewp** [comment]
Moved to over here: https://github.com/canjs/can-stache-define-element/issues/29
